// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDMDln6huattwyEq1CthUtAZvr01pOFeuw",
      authDomain: "cuts-a2ddf.firebaseapp.com",
      projectId: "cuts-a2ddf",
      storageBucket: "cuts-a2ddf.appspot.com",
      messagingSenderId: "481295920928",
      appId: "1:481295920928:web:1ed21ca0b304429ae27145",
      measurementId: "G-57B88KVZ47");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTYwU9D096PrVJb-z28Rj3PWGjcuIiGw',
    appId: '1:481295920928:android:881460d315e6136be27145',
    messagingSenderId: '481295920928',
    projectId: 'cuts-a2ddf',
    storageBucket: 'cuts-a2ddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuQKfEcqXJ3PYQBhXOo_lzFWn0YPCCeBU',
    appId: '1:481295920928:ios:8c62761e60c87d6fe27145',
    messagingSenderId: '481295920928',
    projectId: 'cuts-a2ddf',
    storageBucket: 'cuts-a2ddf.appspot.com',
    androidClientId:
        '481295920928-3aqs1015fupk9dr6kikfi55kode8023j.apps.googleusercontent.com',
    iosClientId:
        '481295920928-kjdvebp0r93htetv2pj3lqttmsbuujvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuts',
  );
}
